# name: Publish Package to npmjs
# on:
#   push:
#     branches: [main]
# jobs:
#   release:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Setup Node
#         uses: actions/setup-node@v3
#         with:
#           node-version: '16.x'
#           registry-url: 'https://npm.pkg.github.com/'
#       - name: Installing dependencies 🔧
#         run: npm ci
#       - name: Checking style 💃
#         run: npm run check
#       - name: Testing 🧪
#         run: npm run build
#       - name: Building 🛠
#         run: npm run build
#       - name: Publishing 📦
#         run: npm publish
#         env:
#           NODE_AUTH_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
